### ISSUE TITLE
Render German Sh 0 and Sh 2 signs at buffer stops/gates

### ISSUE THREAD

**Issue by rurseekatze** [rurseekatze/OpenRailwayMap#177]
Add rendering of German Sh 0 and Sh 2 signs at buffer stops or gates. Currently they are not rendered on the map.

**Comment by JJJWegdam** [comment]
Good initiative! Could you also add the Dutch 243a sign? It is has a similar purpose and is displayed mainly at the top buffer stops.
![Alt Text](http://puu.sh/gYP05/3c44e698ad.png)
![Alt Text](http://upload.wikimedia.org/wikipedia/commons/a/a8/Stootblok_%28staal%29.jpg)


Having something that renders at buffer stops has, in my opinion, priority because it is a more internationally accepted tag. It would immediately cover the world in stead of having to assign signs per country. We could cosider something like the [OSM wiki proposal](https://wiki.openstreetmap.org/wiki/Tag:railway%3Dbuffer_stop#possible_rendering) ![Alt Text](https://wiki.openstreetmap.org/w/images/3/36/Railway_buffer_stop.svg) or like JOSM displays in its presets and assign that to railway=buffer_stop.  
![Alt Text](http://puu.sh/gYOov/bb3e79efb1.png)
