### ISSUE TITLE
Rendering bridges at high zoomlevels

### ISSUE THREAD

**Issue by JJJWegdam** [rurseekatze/OpenRailwayMap#186]
In my opinion, bridges should stop rendering at higher (Länder) zoom levels. I would advice to stop rendering below zoom level 10. 
To give an example: the longest railway bridge that I could find in Europe is between Denmark and Sweden (8,2 km) and renders as big as the hand icon of your mouse at zoom level 10. ;)
![Alt Text](http://www.roadtraffic-technology.com/uploads/feature/feature1952/1-oresund-bridge.jpg)

**Comment by rurseekatze** [comment]
I would suggest the same for tunnels.

Rendering tunnels in low zoomlevels produces disrupted lines that doesn't look very nice: http://www.openrailwaymap.org/mobile.php?lat=44.296332880058706&lon=9.4427490234375&zoom=8&searchquery=&lang=de&style=standard

**Comment by JJJWegdam** [comment]
Agreed. 
I first thought it wasn't necessary to do tunnels aswell, because they render quite well in the Netherlands. Looking at your example though, made me change my mind.

**Comment by DerDakon** [comment]
The [longest bridge](https://en.wikipedia.org/wiki/Danyang–Kunshan_Grand_Bridge) has a length of 164km, that should be visible even at a very small zoom level. And [tunnels of 55km](https://en.wikipedia.org/wiki/Brenner_Base_Tunnel) aren't even that far away.

**Comment by rurseekatze** [comment]
It is correct that the bridges or tunnels can be so long that their length can be visible even in small zoom levels. But this produces disrupted lines because you cannot distinguish long important bridges/tunnels from very small ones. 

If you have a look at other maps, you will see that e.g. Mapnik renders bridges (for example at motorways) in zoom 13 and higher. I think that the developers there had similar problems that influcenced their decision.
