### ISSUE TITLE
Eurobalises

### ISSUE THREAD

**Issue by JJJWegdam** [rurseekatze/OpenRailwayMap#187]
How do we map ERTMS Eurobalises and corresponding signs? I intend to import those (from ProRail) for the Netherlands.

![Alt Text](http://upload.wikimedia.org/wikipedia/commons/f/f9/Repère_sncb.jpg)

**Comment by JJJWegdam** [comment]
Note that a balise-location requires multiple balises per track and only contains a single sign per direction.
Also, balises have different detection systems which could be tagged aswell.

**Comment by Nakaner** [comment]
Please discuss tagging questions at the [mailing list](http://lists.openrailwaymap.org/lists/listinfo/openrailwaymap). You will reach more recipients.

Does the yellow-blue sign serve the same function as the official [ETCS Stop Marker](http://www.sh1.org/eisenbahn/snne.htm)?

**Comment by JJJWegdam** [comment]
Both signs are indeed stop markers. It seems that they can be either an arrow or a triangle.
I closed my other tagging issues by the way, I'll post them to the mailing list soon.
![Alt Text](http://puu.sh/h7Fxd/e4d46ff803.jpg)

**Comment by rurseekatze** [comment]
I will close this issue because tagging questions should be discussed on our mailing list.

Have a look at [a similar signal in Germany](http://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_in_Germany#Ne_14_ETCS-Halt-Tafel_.28ETCS_Stop_marker.29) as an example on how to tag ETCS stop markers in the Netherlands. Then you could propose and discuss a possible tagging scheme for these signs on the mailing list.
