### ISSUE TITLE
Tram bridge render bug

### ISSUE THREAD

**Issue by JJJWegdam** [rurseekatze/OpenRailwayMap#214]
Tram bridges keep rendering after zoom 10, while their respective tram lines stop rendering at those zoom levels.

![Alt text](http://puu.sh/huolR/ce4a67fc00.PNG)

**Comment by DerDakon** [comment]
The same happens with tunnels:
-check Hannover in zoom level 10, the city is white because of the tram tunnels
-check the new highspeed line Erfurt-Nürnberg, that is currently under construction: at zoom level 8 you only see white areas where the tunnels will be: http://www.openrailwaymap.org/?lang=de&lat=50.47045290840598&lon=11.006326675415039&zoom=13&style=standard (zoom out)
