### ISSUE TITLE
Icons for Ks signals

### ISSUE THREAD

**Issue by PeterDRS** [rurseekatze/OpenRailwayMap#269]
Ks signals should have a Ne 2 icon analogous to Hl signals when they have a Ne 2 in reality.

That is the case when they are distant signals and not repeaters and not combined signals.

**Comment by Nakaner** [comment]
I oppose this pull request. Hl signals only have a Ne 2 in their icon because there is no other possibility to distinguish between Hl distant signals from other symbols. Our symbols are designed to be near reality but they still have to be readable at low resolutions. That's why usage of Ne 2 in distant signal icons should be avoided.

You just created this issue because wrong tagged signals (signals with `railway:signal:main=DE-ESO:ks` + `railway:signal:distant=DE-ESO:ks`) are not rendered the way you want.

**Comment by PeterDRS** [comment]
First, it is not a pull request but an issue.
Second, I have an icon but cannot upload it here in the web browser.
Third, the idea was from yesterday, it does not have to do with the new tagging scheme.
Fourth, when rendering the Ne 2 with Hl signals, it would be consequent to do so with Ks signals.

Unfortunately, I feel like in war and Nakaner is the enemy. His aim is to "block" me consequently to avoid an improvement of the ORM. Nakaner does not want to say "It was the idea of someone else", I oppose.

Or why are my improvement proposels be so aggressivly attacked?

**Comment by rurseekatze** [comment]
It is difficult to create signal icons that are both very realistic and detailled as well as readable in low resolutions and small icon sizes.

When we designed the German signal icons, we decided to add a Ne 2 sign to Hl signals to make it distinguishable from other Hl signals. For other signals such as type Ks this is not necessary, so we dropped the Ne 2 sign.

If you have designed an icon with a Ne 2 sign that is good to read on a map, I would like to see it. Simply attach it here, post a link to another storage, etc.

P.S.: If your suggestions are not accepted, then there are no personal reasons for that. You have to accept that issues usually need some discussion and further improvements, and some issues may be rejected. That is not related to your person. And I don't think that Nakaner is against your issues because they are suggested by you. He always explained his arguments and his point of view. Maybe his very direct way of communication is not easy for some people...

**Comment by PeterDRS** [comment]
![de-ks-distant-32](https://cloud.githubusercontent.com/assets/13511519/8940563/f23c429e-356a-11e5-9a8b-98d824be2b16.png)

I just took the Ne2 from the Hl symbol.

I don't understand what the difference to Hl signals are. Both Hl and Ks signals are not unique with the colour yellow.

Beside that, I don't do my proposals for fun, but they have a serious background.

E.g. the transition from combined to main+distant is fundamental for implementing tools that need the main aspects of a signal. They won't work as efficient when they manually have to divide a combined signal again.

**Comment by Nakaner** [comment]
Your icon will be only 10 x 16 pixel on the map! ![Ks distant 16 px high](https://raw.githubusercontent.com/rurseekatze/OpenRailwayMap/master/styles/icons/de-ks-distant-repeated-16.png)

> I don't understand what the difference to Hl signals are. Both Hl and Ks signals are not unique with the colour yellow.

Inside one country each icon should only have one meaning (it's a very basic rule of cartography, isn't it?). For example, a black rectangle with a red dot is
* an Hp light signal without `railway:signal:main:states=*` if the dot is at the upper left of the rectangle
* an Ks combined signal if the dot is at the top (in the center) of the rectangle
* an Sv signal which can show Hp 0 if the dot is at the bottom of the rectangle
* an Hl signal (I don't know what exactl – look it up at the source code) if the dot is in the middle of the rectangle

Another example: A black rectangle with a green dot is
* an Hp signal which cannot show Hp 2 if the dot is at the upper left
* an Ks main signal if the dot is at the center of the rectangle
* an Hl main signal which cannot display Hl 2, Hl 3a and Hl 3b if the dot is at the upper right
* an Hl distant signal if the dot is at the upper right and the icon has a Ne 2 sign

I am the designer of these icons and the guy who spend hours to create a way to display as much information about those horrible complicated Hl signalling system (H/V is complicated, too). I think that using Ne 2 inside the icons does not fit to the corporate identity of the whole icon set. Icons are simplifications of the reality (that's why semaphore Hp icons look as the look).

**Comment by PeterDRS** [comment]
That is too complicated for me.

And the best thing is the Ks signal with Hp0 (red) and a marker light in the top. That is a combination that should never occur.

But I see that OpenRailwayMap seems to be a project of "graphic" junkies who do not care about functionality and real railway (scientific) backgrounds.

**Comment by Nakaner** [comment]
> And the best thing is the Ks signal with Hp0 (red) and a marker light in the top. That is a combination that should never occur.

I knew that red + white light is illegal at the time I wrote that MapCSS rule. But I had to choose between the devil and the deep blue sea.

If I want to show the additional light (reduced distance) of Ks combined signals, I have to use a yellow dot for Ks combined signals. This would conflict with the usage of the yellow light at Ks distant signals. This would force me to use a green light at Ks distant signals. This would force me to use a red light at Ks main signals. This would conflict with Hl 0. I thought that a conflict is worse than a "illegal" icon.

Please suggest which MapCSS rule should display which icon if you have a great idea.

**Comment by PeterDRS** [comment]
First of all you have to use the Ne2 to capsulate all pure distant signals away.

Than you can distinguish between main and main+distant by using green or yellow light.

Better would be to have all signals in red order and show the "Mastschilder". ;)

I don't care much about the rendering. For me it is much more important to have clean and clear DATA (incl. a suitable SCHEME!) in the background. That's more important than these silly icons.

**Comment by rurseekatze** [comment]
> I don't care much about the rendering. For me it is much more important to have clean and clear DATA (incl. a suitable SCHEME!) in the background. That's more important than these silly icons.

Why do you suggest rendering changes if you are not interested in rendering and "silly icons"?

**Comment by PeterDRS** [comment]
I meant that the tagging scheme should not be optimized for rendering.
