### ISSUE TITLE
Hl signal not rendered

### ISSUE THREAD

**Issue by PeterDRS** [rurseekatze/OpenRailwayMap#301]
The Hl signal node 2768502517 is not rendered.

**Comment by Nakaner** [comment]
It looks like a bug at our style sheet because tagging does not look worse. The code which rules Hl signal appearance is very complicated due to the many signal aspects the Hl signal system has. I have to have a deeper a look at the code (it's written by myself) to find and eliminate the bug. This will happen after my holiday (i.e. next week).

**Comment by PeterDRS** [comment]
OpenRailwayMap has bugs?

That's impossible (as long as it is Nakaners code)!

**Comment by PeterDRS** [comment]
Hl distant repeaters should be rendered too.

**Comment by DerDakon** [comment]
This combination of states simply does not match any rendering rules. I suggest to change the first rules ([!"railway:signal:combined:states"]) to simply ignore any states. The more specific tagging rules follow and would render the other well-defined cases, and this one would render the rest. Rendering only those without given states, but not those with unmatched combinations of states doesn't make sense to me.

**Comment by PeterDRS** [comment]
> well-defined cases

But I have to say that the states are the states that occur in reality.
