### ISSUE TITLE
Missing icons of JOSM preset

### ISSUE THREAD

**Issue by Klumbumbus** [rurseekatze/OpenRailwayMap#387]
The JOSM presets use icons, which are not availible, which produces errors in the JOSM statusreport, see https://josm.openstreetmap.de/ticket/11980#comment:6

**Comment by don-vip** [comment]
Hi,
We have now a unit test that detects invalid presets:
https://josm.openstreetmap.de/jenkins/job/JOSM/jdk=JDK7/lastUnsuccessfulBuild/testReport/junit/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTest/testValidityOfAvailablePresets/

OpenRailwayMap ones generate a lot of errors due to missing icons.

Can you please provide a zip archive containing all the missing icons?

**Comment by don-vip** [comment]
The Makefile should also detect missing icons, like in f7783567ed1ef2124b354319a9f9f1cbbf2b56ab for styles.

**Comment by rurseekatze** [comment]
In https://github.com/rurseekatze/OpenRailwayMap/commit/f4778127b4402f4f97406952ae92daf9f9a33835 I have extended the existing Makefile, so that now it can generate zip archives containing all icons.

The new zip archives are available under http://www.openrailwaymap.org/josm-presets/. I have already updated the URLs of our presets  at https://josm.openstreetmap.de/wiki/PresetsSource.

Currently the Makefile simply adds all icons to the archive, ignoring whether they are used or not. In a later version, it will parse a list of all used icons from the preset file and add only these icons to the archive for generating smaller files.

> The Makefile should also detect missing icons, like in f778356 for styles.

If the unit test detects no problems any more, I would close this issue and create a new one for extending the Makefile to detect missing icons.

**Comment by don-vip** [comment]
Thanks! :)

**Comment by don-vip** [comment]
There are still some errors.

**Comment by DerDakon** [comment]
Some icon references were fixed in #407. What's definitely missing are icons for the Sk signals, they just do not exist. In #409 I have changed the generation to only include those icons in the ZIPs that are actually referenced.

**Comment by rurseekatze** [comment]
There were still a lot of items with invalid icon references. The items had placeholder icon references too, but they were already the names of the planned icons instead of `todo.png`.

In https://github.com/rurseekatze/OpenRailwayMap/commit/550a77ac3f9421a10a914ef19d7b464bb5ff7430 I removed all of these icon references. Now there should not be any errors anymore.

**Comment by rurseekatze** [comment]
Can this issue be closed?

**Comment by don-vip** [comment]
Yes, all errors are gone now :) Thank you!
