### ISSUE TITLE
Render ways as stations

### ISSUE THREAD

**Issue by margin-auto** [rurseekatze/OpenRailwayMap#464]
Railway=station is only rendered when this tag is attached to a *node* but not to a way. If e.g. the station building is mapped as a (closed) way and railway=station is attached to this way this station isn't rendered on the map (if there is no additional single node). For example Sarrebourg: https://www.openstreetmap.org/way/44697686

I'd suggest to add this rendering to ORM.

**Comment by rurseekatze** [comment]
Due to different reasons, we decided to map stations just as nodes and documented that in the tagging schema.

The example Sarrebourg shows one of the problems that occurs with stations mapped as areas: The station label is not placed in the center of the station, but at the side of the station. 

The station Sarrebourg should be mapped with a station-node at the center of the station and with `building=train_station` at the station building.

Therefore OpenRailwayMap will not add support to render stations mapped as areas.

**Comment by margin-auto** [comment]
OK... *sigh*
![bildschirmfoto vom 2016-03-06 11 07 04](https://cloud.githubusercontent.com/assets/17515478/13553487/c1470708-e38b-11e5-8373-38faf5f5defe.png)
