### ISSUE TITLE
maxspeeds not shown for construction

### ISSUE THREAD

**Issue by bigbug21** [rurseekatze/OpenRailwayMap#552]
In many cases, maxspeeds for railways tagged with railway=construction are not shown on the map.

One of many examples is the new Stuttgart central station: http://www.openrailwaymap.org/?lang=&lat=48.7843885334358&lon=9.186480045318604&zoom=16&style=maxspeed

**Comment by Nakaner** [comment]
That's a bug, not a feature because you (or someone else) has already added `construction=rail` to the tracks. Unfortunately, the style currently only supports `construction:railway=rail`. The style forces you to add `construction:railway=rail` to be able to distinguish between "normal" railway tracks, tram tracks, light rail tracks (all under construction) etc.

**Comment by DerDakon** [comment]
Should be fixed by the combination of #527 and #496.

**Comment by rurseekatze** [comment]
#527 was merged and fixes the rendering issue. @bigbug21, can you confirm this?

#496 has to be rebased before it can be merged, too.

**Comment by bigbug21** [comment]
Yes, it aparently works fine now!
